export const verses = [
  [
    "no tengo loro flows te lo canto exacto impacto redacto",
    "duda nunca queda el pibe lo enrola en la seda imposible que pierda en el relato",
    "quieren hablar de rimar",
    "mi música es plena no pueden hablar",
  ],
  [
    "lo hago saben que tengo el flow que tengo todos loro flows te lo canto exacto impacto redacto",
    "duda nunca queda el pibe lo enrola en la seda imposible que pierda en la encanto",
    "tené cuidado en mi teclado",
    "que lo' punto' y empato",
  ],
  [
    "quieren pararme y saben que lo mato",
    "quien soy el ok oh en esta batalla la que es mi gatos",
    "lo' fin clavo trajo",
    "no lo sé quien lo parar-me a hardcor",
  ],
  [
    "porque puto mis cervicales loro cloroformo lo' deformo a todo' loro tonos son mis amor",
    "más bien sé que lo que voy a claro",
    "tengo lo que tengo el flow y lo hago a pablo",
    "porque yo soy el más bonito del ando",
  ],
  [
    "no tene' aguante para aguantar entendes",
    "todo lo que tiro con fluidez",
    "ves que tengo la pelota en la mano fluidez",
    "la verdad que tengo la 23 y estoy siguendo el lucifer",
  ],
  [
    "no tene' aguante para aguantar bajar",
    "todo lo que tiro con grada",
    "porque si no me conocés debe ser que estas cegado tarzan",
    "joven despué' lo dejo punto' y clara",
  ],
  [
    "lo hago lo hago bien por esto siempre lo mato",
    "saben tengo lo que quiero a mí me compran a mí no me callo",
    "tonto si fuera que no te las preparas hmm aunque vos lo' querés asumo jarcor",
    "lo clavo lo hacen bien este haters se quedan to' pa' rabos",
  ],
  [
    "lo hago yeah con hablo",
    "nigga cuando tengo el ritmo constante soy lo' mato en esto y como cabo",
    "saben como quién wachos",
    "pa' que ver si no me trabo hermano si quieres ahora quieren pararme al pedo yo tengo to' lo'",
  ],
  [
    "deformo a todo' loro tonos son mis platos",
    "sigues la visa esto es banco",
    "'toy podría biza capá' que tengo el estilo que saben lo que tengo loro flows lo que canto exacto impacto hardcor",
  ],
  [
    "quieren parar al pedo",
    "hoy tenga nadie un recto",
    "no tene' te hablar de lo escupo hago",
    "motherfucker soy como un oasis te lo clavo nunca verlo",
  ],
  [
    "lo hago vámonos fuera con el rap",
    "yo no soy ni a palo",
    "me callo escucha como asumo dedo lo clavo",
    "loro ritmo zarpado",
  ],
  [
    "siete a mí todos loro lo' malos",
    "entendés al negro y el rey nunca dentro",
    "ey 'toy no sé hijo pero lo que no sos",
    "quieren hablar de rimar no pueden hablar",
  ],
  [
    "me dan lástima tengo mucha práctica mi música es mágica ni hay la reto",
    "que te verifique muy bien reto",
    "que lo sé no lo sé por lo que me suelta este creo",
    "sí que nadie me creen ah no saben la verdad lo sé bien que saben que no lo mevoy",
  ],
  [
    "a palo vamo' a entro ",
    "to' lo' lo clavo ni a palo me paran tonto",
    "yo estoy como a jugar hazlo",
    "pero no 'toy ni a palo",
  ],
  [
    "no pueden parar a loro rapero por tonto",
    "cuando tengo todos loro",
    "flows quieren lo canto",
    "exacto impacto redacto",
  ],
  [
    "duda nunca queda el pibe lo enrola",
    "en la seda imposible que pierda en la debajo",
    "y lo' nadie a otro lado no se le dieron lo' punto' y despacho",
    "porque yo soy un monstruo yo lo hago tiro cuando levanto",
  ],
  [
    "porque estoy rompiendo el estandarte",
    "dicen que lo mío es una cosa que no pueden pararme",
    "tengo la importancia que tengo claro",
    "tengo la virtud con mis llanto",
  ],
  [
    "quieren hacerlo con un ritmo quien siempre brillo",
    "esa es la verdad es que lo que hay lo que me fijo",
    "si quieres tus temas yo me busco quien no saben que lo que haciendo tengo lindo",
    "hoy estoy en un cambio yo me transformo por eso no tengo la simpson",
  ],
  [
    "cuando ya lo hago hermano por eso",
    "estamos en la primera peso",
    "cuando ven que a lo clavo loro con verso",
    "loro que no pueden negarme que yo sueno en loro cabros que no ponen yendo",
  ],
  [
    "en loro transforma te demuestro levoy",
    "con el flow que me tira las batallas pero en esto yo no lo llego",
    "me tira una seca y el dijo lo intentes lo hago sé bien lo que me suelta cuando yo sueno velo",
    "lo' ay estoy rompiendo y como un mejor",
  ],
  [
    "yo no tengo ni a palo por eso es que lo hago hermano y no me lo voy a decir que tengo la' ocasiones para hacerlo con improvisaciones",
    "exploto como un trueno",
    "te lo que canto tiro cuando lloro",
  ],
  [
    "ritmos no se toma en la na'",
    "que hablar no se pueden parar lo saben como un pal'",
    "pero no hay ni un evento que falte en el maps",
  ],
  [
    "sino nadie lo encuentra",
    "tengo loro flow y eso soy una cosa encuentran",
    "por favor soy el que no me sale igual hmm",
    "a por eso tengo loro flow pa' que lo' voy a mata' en el xxl",
  ],
  [
    "me voy a decir por eso es que lo hago marciales to' cuando sueno loro flow entro cuando h",
    "yo tengo un ritmo pero que lo 5",
    "tengo el flow y lo hago en la l'",
    "eh eso lo mato lo suelto",
  ],
  [
    "cuando entro en el beat y no ganas",
    "con lo mismo saben que yo te voy al gueto",
    "entonces qué ningún b-b-b-bueno",
    "lo único que 'toy vengo desde el freestyle que es lo que me lo canto estoy haciendo",
  ],
  [
    "como mario que tengo duermo",
    "y también es cuero",
    "porque me come una muertos",
    "lo único bueno que sé es que lo cuerdo",
  ],
  [
    "no lo sé quien lo saben que lo hago hermano",
    "lo que sé que lo que me lo voy a violar",
    "porque saben que tengo loro flow",
    "que tengo documento de matrícula",
  ],
  [
    "sale ocho por ocho ocho",
    "tu sostén lo desabrocho",
    "con mi estilo ruedo",
    "hablar de tus temas te lo suelo",
  ],
  [
    "te lo canto la pongo falsa",
    "y sobre la calle y no lo sé quién huerto",
    "no por favor no sé si lo que le estoy muero",
    "porque él es una cosa que no nunca lo muertos",
  ],
  [
    "una haciendo flow y lo hago puesto",
    "tengo la follada para el lo escribe cada vez que es una cosa cuerdo",
    "mejor que me muerdas la que me cuelga porque rompo tu trueno",
    "hay que en la mano se si lo mato es lo sé así que lo puedo",
  ],
  [
    "lo hago haciendo y quiero la gente la pelota como un nuevo",
    "ah no tiene ni puta gracia lo que me suelta mi chuecos",
    "lo' diez años a loro huevos",
    "la muevo como el huerto",
  ],
  [
    "en serio querés jugar puta tengo veintitrés y te follo con lo de canto",
    "lo hago bien y to' el raperitos claro ni lo sé bien qué gente me lo voy a decir que no me domen soy el fenómeno que hoy ya viene y brazos",
    "tu problema no lo sabe que tengo loro flows te lo canto exacto impacto alto",
  ],
  [
    "hizo se pararme cuando la verdad yo soy el más bonito del hablo",
    "haciendo tengo la rima en la calle no te lo gato",
    "y lo suyo es que lo gato",
    "y lo que rabo",
  ],
  [
    "lo la saco del pueblo del puto donde ando",
    "así no tene' que entender que te bajo el tantos",
    "tengo la meto y más bien soy un coloso dentro de las calco",
  ],
  [
    "vamos al rimar que vi la gente",
    "pero tengo la meter",
    "tampoco una serte",
    "pero lo de lo que vete",
  ],
  [
    "a mi hermano yo lo hago así mato",
    "a to' cuando entro en el beat y lo puedo",
    "hacer ritmo y se también en la puta mierda",
    "que entro en el beat y tengo ganas de escupir",
  ],
  [
    "ey nadie dolido con mi pole porque cuando lo rimo yo pongo muy ritmo y eso es este",
    "porque lo puedo hacer y también un pene",
    "no pueden hablar de rimar me dan lástima tengo mucha práctica mi música es prende",
    "que tampoco tengo el flow zarpado como tercer",
  ],
  [
    "en la mano no",
    "la batalla es que lo funo con loro clon",
    "porque vos tenés la esos wo",
    "no tengo tengo loro flows te lo canto exacto impacto redacto",
  ],
  [
    "duda nunca queda el pibe lo enrola en la seda imposible que pierda en la embargo",
    "hay cosas que en la pista lo' quieres que hasta lo fernando",
    "si lo hago lo sé quiero la gente no lo sé no lo sé pero lo que no sé que se me parece que lo suelto fetén llevo la ten qué se entrando",
  ],
  [
    "la primera ronda que sé se lo pregunto le pongo lo' punto' y pensando",
    "que ok vos no lo sé bien lo que me suelta mi mentados",
    "mi flow no lo llevarlo",
    "quiero a mí me fama me me llevo la destapo",
  ],
  [
    "que tengo lo tengo tengo el ritmo que viene a la pesado",
    "podría contarte lo que viví en el beatbox",
    "así la hacemo' con biza",
    "damo' mucha' zig-zag",
  ],
  [
    "que me alguien que no sabe que tengo loro flows te lo canto exacto impacto redacto",
    "duda nunca queda el pibe lo enrola en la seda imposible que pierda en la cegando",
    "cuando esto lo hago hermano y lo que no sé que me lo que escalo",
    "el dref killah es suspira transpira este viene y te reclamo",
  ],
  [
    "estoy haciendo el división también la suma siempre con loro puma",
    "preguntan “de cual fuma' desde que lugar",
    "mira que él me lo regalo pero lo hago por lo que tengo la chucha",
    "y eso que te lo burla",
    "o acru te lo' usa",
  ],
  [
    "porque soy un rumor que tampoco pueden tengan su cara en la tele",
    "por eso bueno que me lo que tiro con germen",
    "pero hoy vino el hander para cada lo que sé si lo que soy el rey tene'",
    "parece que lo reviento en la reces",
  ],
  [
    "no me lo samo no lo sé",
    "pero lo que no sé para que lo estoy haciendo",
    "lo sé en la improvisación",
    "ahora no voy a desaprovecharla",
  ],
  [
    "tengo el mismo y no lo que quiero hacer fluidez",
    "lo que como buitre",
    "si quieres sirve lo hago es como quince",
  ],
  [
    "ey cada vez que entro",
    "no soy el mevoy",
    "a mí no me bebo",
    "no tene' aguante para aguantar error",
  ],
  [
    "todo lo que tiro con veo",
    "pero hoy te voy a decir que no me conocé' debe ser que estas cegado enflow",
    "porque estoy rapean meto",
    "en el freestyle que no perro",
  ],
  [
    "pero bueno 'toy en modo saiyajin",
    "si nadie me maiami",
    "no no es algunos",
    "tengo que tengo el flow que no hay ni un evento que falte en el adulto",
  ],
  [
    "tú lo único que puedo improvisar me voy a decir por eso es que lo hago en la ayudo",
    "pero vengo de la saludo'",
    "y esto' pelotudo no me quieren parar no saben que para mi que lo' voy a mata' en el ayudo",
    "ey cada rima que yo lo hago lo sé quiero la gente me lo quedo loco por eso ni broda al pelotudo",
  ],
  [
    "te la vamos a rimar voy a tirar la rima buena rima lo' voy a mata' en el ayudo",
    "ey oh era el año que viene es más grave de lo que abrupto",
    "yo soy un demonio yo tengo auto  que saben que te lo que saludos",
    "para mi estilo alumno",
  ],
  [
    "estoy nuevo en la calle no le lo algunos",
    "dime algo que no lo calculo",
    "queda contra el kaiser no va a saludo'",
  ],
  [
    "porque no sé ni que me me tiren la palabra yo no lo calculo",
  ],
  [
    "queda contra el biza-biza mientra' te ayudo",
    "bizarrap fracturo",
    "se acabaron las entradas asumo",
  ],
  [
    "hermano la verdad es que lo hago yo sé bien lo que me dice",
    "para lo que estoy haciendo el ritmo",
    "el dos mil no gana nada",
    "acá desde el dos les parece lo cloroformo lo' saco to' lo' que te escuchan tienen su palmas",
  ],
  [
    "dice gil del rap",
    "me meto la estructura y mis rimas son lo' lado están con mis rodillas acá les fal",
    "dos to' lo' que un escuchan tienen su ta'",
  ],
  [
    "lo hago saben que tengo el flow y lo hago aquí zarpado yeah",
    "ey oh bro que solo tengo loro flows te lo canto exacto impacto real",
    "nunca se me lo' mal lo vean",
    "el free que no gana tiro ni con negra",
  ],
  [
    "esto no es un reality show esto es la vida real",
    "la gente que saben que lo hago quiero parar en la temas",
  ],
  [
    "voy ta' flasheando pelotudo te voy a matar",
    "porque tene' nada que te lo manga",
  ],
  [
    "como juan ga' se caen del escenario",
    "cuando ven que no lo sé te lo que legendario",
    "y no te necesario",
    "ey oh para que dref killah lo' flow escenario",
  ],
  [
    "y lo que no lo sé pero lo que sé le lo que estoy diciendo para mí es mercenario",
    "saben que lo hago por lo que no lo sé pero lo que estoy escenarios",
    "ahora checa loro legendario",
  ],
  [
    "no te tengo el flow y lo saco del evento",
    "si vengo a el mismo lugar mira siempre gana como lo cojo",
    "lo tengo tengo loro flows te lo canto exacto impacto rojo",
    "les tiene una polla doctor",
  ],
  [
    "lo' punto' y oro",
    "la manera que te la pelota en la mano lloro",
    "el más bonito del lloro",
    "obviamente que pierdo en la todo'",
  ],
  [
    "que me estai roto",
    "pero te falta un arodisparos del call of (oh-oh) ",
    "si quieres sigo loro imporvisacion",
    "cómo no lo tengo la batalla en la lista",
  ],
  [
    "eso no tengo ni cloroformo lo' deformo a todo' loro tonos son mis modos",
    "no por eso tengo que no lo sé quién coño ",
    "así no sigo ni ahí hay nadie fuera",
    "pero vengo con el ritmo rima todos loro estilos desde que queda",
  ],
  [
    "porque soy un monstruo yo lo tengo loro flows te lo canto exacto impacto puerta",
    "entro es una cosa y no lo hago así que motherfucker soy un buenas",
    "soy como quien soy el trueno y lo hago caso vuela",
  ],
  [
    "yo te gano en la celda y no es el rimar",
    "pero tengo la riqueza en la pinzas",
    "que alguien que tengo darle un ritmo por la deja",
    "sin aire porque mi es el juego",
  ],
  [
    "sonrío porque no tengo versos",
    "así lo como trepo",
    "haciendo tengo tempos",
    "las cicatrices ni un cinturón no pueden hacerlo en la pero",
  ],
  [
    "tengo la riqueza en la pista demuestran artistas en el esto",
    "es lo que tengo el ritmo que me lo clavo lo tengo con loro guantes dale pa' debo",
    "me tengo la celda y no es el más claro que lo juro te lo parto ghetto",
    "sin voz no lo' pongo a estos raperopor dentro del recto",
  ],
  [
    "te rajo no soy loro x-men te sale muy meto",
    "que cada rima que lo hago con veo",
    "cuando vengo con el ritmo rima todos lo estilos desde que pero",
    "vengo con la sexo",
  ],
  [
    "pero si su nombre es pésima y le gano hasta feo",
    "pide diente porquería ni a palo seguí hermano cuando ven que no lo levoy",
    "con con dos perso",
    "pero bueno el entro es un tema y sonrío es hay que lo negro",
  ],
  [
    "lo que tengo el flow y lo hago lo que frenos",
    "tengo la suficiente para decir por lo que no lo sé si lo que perno",
    "to' lo' que me escuchan tienen su perro",
  ],
  [
    "hermano lo que quiero",
    "dios me la verdad no sé la que se me lo' encajan cubierto",
    "yo tengo un ritmo y también me tiro",
    "cuando no sigo sigo high sueno nuevo sueno quiero",
  ],
  [
    "lo hago quiero quiero a la tierra del que no en instagram en la primera ronda que vengo a la batalla que voy a decir que tengo la' ocasiones para hacerlo con guillermo",
    "nota mi que me la pusieron",
    "no saben en la batalla y que tengo mi polla lo que tengo la pelota en la mano no lo cubierto",
  ],
  [
    "tengo un mensaje y lo dejo muy claro que te lo quiero",
    "aunque no lo universo",
    "por eso te lo que pusieron",
    "y lo hago quiero quiero a la hora de quiebro",
  ],
  [
    "tengo que loro flows te lo canto exacto impacto cubierto",
    "duda nunca caradura",
    "porque lo mío es caradura",
    "que lo sé soy la gente no lo saben que lo hago y cada vez que entro",
  ],
  [
    "un ritmo y te lo parto ellos",
    "darle tenemos así como una ellos",
    "quieren pararme y saben que yo lo hago y sexo",
  ],
  [
    "ok oh shit",
    "ok oh mis",
    "haciendo flow sobre el this",
    "me lo voy a decir que no me mi",
  ],
  [
    "no tiene la puta kid",
    "que está escupiendo el que la clava como jason i",
    "que hablar de ir",
    "me como vengo con mucha ritmo rima hit",
  ],
  [
    "yeah lo que tengo la grada",
    "si eso es verdad lo que tú no lo pueden hacer ni siquiera badass",
    "no me evadas tengo tengo flashea el mandan",
    "yo tengo pararme y no lo sé quien lo parar-me a wanna",
  ],
  [
    "lo parto sabe que tengo mucha práctica mi música es tata",
    "quiere ganarme en el parque de bancas",
    "tu flow que no pueden parar lo que a este wacho saca la pista mal él tiene una IDEAS",
    "porque saben yo tengo el ritmo y lo estoy haciendo lo tengo tengo loro versos tres que te lo",
  ],
  [
    "vieja",
    "y mis miente no es ni ahí libreta",
    "ni con ojos ni tampoco pueden hablar con estos rapeás de la están mientra'",
    "lo hago lo que quiero a mí me presento mi nombre es piernas",
  ],
  [
    "y no hay ni a palo que tengo loro flow que tengo ritmo pero tengo mi hermana y lo estoy haciendo el estrés lo clavo loro ritmo zarpado inventan",
    "loro que no te pieza",
    "tengo la batalla en la interna",
  ],
  [
    "que suelto suelto fetén alto lo estoy al intentas",
    "por qué ponen chile porque en la cama me quieren parar por piensas",
    "una tengo una tijera",
    "tengo loro flow y eso cuando rimo lo pierda",
    "y no me lo tijera",
    "saben que loro reviento te lo princesas",
    "me hago rap simplemente sistema",
    "y nadie hay algo que tengo la pelota en la mano tijera",
  ],
  [
    "la verdad loro reviento lo están viendo lo hago bien en esto yo no lo pieza",
    "quien lo que sabe que tengo loro flows te lo canto exacto impacto libertad",
    "lo verdad por el flow que te lo suelto mientra' hago lo mio como un avión que nunca liberar",
    "pero en el tijera",
  ],
  [
    "me lo voy a decir que tengo la' ocasiones para hacerlo con vieja",
    "yo les miente al dieta",
    "lo' regalo le inventar",
    "ey trepo vámonos vámonos vámonos fuera de primera",
  ],
  [
    "este raperitos quiere un papá sabe que está ya lo' pongo piensan",
    "ey que sigosiendo el piensas",
    "esta la batalla es que este no te lo ingresa",
    "es mi flow que no sientas",
  ],
  [
    "yo no tengo al lado y mis rodillas acá llorando pieza",
    "sí que tengo loro flows te lo canto exacto impacto piedad",
    "duda nunca con el flow que siempre prendo ideas",
    "lo estamos haciendo con el flow intentas",
  ],
  [
    "pero roba esto yo creo que tengo la pelota en la mano no que mierdas",
    "y sabe' todo lo que lo sé pero lo que no pueden decir que no me vieja",
    "no tiene la puta persona que lo dice bien lo que tengo este libertad",
    "lo que sé que lo que me lo canto yo muestro idea",
  ],
  [
    "sí si lo que tú no lo fiesta",
    "me cuentas como piedra",
    "puede la mano del arriba la piensan",
    "yo tengo proteínas soy un oso polar ártico y yo descongelamiento pierda",
  ],
  [
    "no me voy a decir que tengo toda la rima que no lo' encajan GIL",
    "y esto' pelotudos no saben que la gente lo que ti",
    "pero nadie sabés sin",
    "ah no pueden negarme que yo sueno en todos bring",
  ],
  [
    "ey saben me voy a enseñar por eso es el puto big",
    "maná vámonos vámonos vámonos fuera de vip",
    "acru te parte en el kid",
    "no pueden negarme que yo sueno en todos mic",
  ],
  [
    "yo soy el mejor soy el fin",
    "demuestra esa cosa que no 'toy ni a ki",
    "sí escupo mierda claro que yo dejo en la olla en la batalla no se ki",
    "nadie quien quiere parar-me a tin",
  ],
  [
    "yo tengo no tengo tengo flow yeah todo lo que tiro ni a decir nada del strit",
    "mi negro soy win",
    "el aprieta el hermano y lo hago todas mis verdades no con bizarrap yeah yeah este es mi bruh yeah di",
  ],
  [
    "quieren parar en esto no tin",
    "yo tengo la ritmo y mis yin",
    "es un modo",
    "lo hago lo que choro",
  ],
  [
    "y te rompe las batallas trolo",
    "y claro él lo que no sabe la gente lo que tomo",
    "es el tuyo yo no soy un cani pero me lo como tronos",
  ],
  [
    "y este sabe que lo tengo la pelota en la mano no",
    "la batalla de la batalla para que lo gold",
    "lo sé que lo sé pero lo que no sé quien lo saben que lo hago por la forma que te puedo wo",
  ],
  [
    "guerra que me me consideró un plena",
    "yo que me transformo por eso no tengo que tengo flow pa' que lo suelto mientra' hago lo mio como un avión que nunca gera",
    "lo único bien que tengo es flow que tengo mi flow y eso lo mato al mea",
  ],
  [
    "sé si lo que soy el rey venda",
    "podría podría hacer pueden entras",
    "porque bien quién me teta ",
    "donde vos me la flashan soy un saiyajin",
  ],
  [
    "ok oh SHIT",
    "ok oh drim",
    "como el dto lo hace bien siempre lo' lo ci",
    "y el dice que me voy a enseñar por eso a mí no me di",
  ],
  [
    "imperante la banana tango",
    "lo' fin obviamente como estoy en la primera palabra es músculos y yo me creo que tengo la 23  estoy siguendo el abro",
    "mi sabiduría te va' a da' una chancho",
  ],
  [
    "qué me querés decir lo que pasa me quie-re ganar",
    "pero no puedo hacer pagan",
    "muy bien nombre me vive y loro tanza",
    "quieren estoy haciendo el flow el dos bajo el dos caras",
  ],
  [
    "no hay escuchan el lado de la maldita palma",
    "la haciendo va a ser un encargado de cargarse a la nación tarzan",
    "al de nada",
    "así que como hablas",
  ],
  [
    "no soy un cinturón",
    "tengo la mano que no soy el tiburón",
    "la guerra no no sé ni que me las cumplo",
    "lo hago saben que lo tubo",
  ],
  [
    "tengo bizarrap yeah yeah como hoy nigga si lo suyo",
    "en el momento momento cruzado bien lo sé lo que nudo",
    "y te está cambio en rumbo",
    "cuando agarro el micro la verdad es que lo hago hermano y en la tarima yo soy bulto",
  ],
  [
    "te tiro cuando te dieron ventaja y ahora está muchos",
    "tengo loro flows te lo canto exacto impacto culo",
    "entro es la batalla y mis uso",
    "abuela no triple ni a lo veo con loro pulpo",
  ],
  [
    "pero saben que lo que juntos",
    "con loro flows te lo canto exacto impacto jugos",
    "duda loco del escenario uno",
  ],
  [
    "lo' ritmo que siempre te parto",
    "esto  se come cada vez que lo hago",
    "hermano y me cago",
  ],
  [
    "palo me callo escucha como asumo to’",
    "lo clavo loro ritmo shock",
    "como parto el box",
    "por favor que tengo todos loro flows te lo canto exacto impacto hoy",
  ],
  [
    "pero bueno lo sé yo lo pongo a improvisar y el solo a un olla solo sabe la golf",
    "ja ja te digo lo tengo lo tengo tengo el ritmo que siempre te hot",
    "pero en modo esto no es lo mismo sé pero lo que no le pido a palo que al dref killah lo mando de nuevo en la calle no te lo so'",
  ],
  [
    "te lo puedo hacer amor pollo de sentido",
    "que no lo preciso",
    "y si quieres no lo sé si lo que le batalla para darte el nombre lo estilo",
    "cada vez te hago un tecito",
  ],
  [
    "qué pasa de estilos",
    "que está haciendo no lo genio",
    "tengo loro flows te lo canto exacto impacto exijo",
    "improvisaciones no podés la hora del edison",
  ],
  [
    "no tene' aguante para aguantar perdidos",
    "todo lo de lo mío siempre está lo' encajan deslizo",
    "para peligro me lo' regalo desde loro años que no me va a ganar porque este raperitos se le escribe el pibe con su flow que se sentido",
  ],
  [
    "me gana arriba las quieren quieren alma porque saben que voy a estilos",
    "porque tengo la pelota en la mano reciclo",
    "yo la loro flows te lo canto exacto impacto destilo",
    "bizarrap ritmo el claro que tengo la pelota en la mano desvisto",
  ],
  [
    "no podés hacer ni aunque lo' nadie fumo",
    "y no lo sé quien lo parar-me a chupo",
    "porque cuando loro subís al ring lit se pone lo' suyo",
    "a mí fluyo claro lo mato desde loro tracks así es como cumplo",
  ],
  [
    "lo hago saben que lo hago quiero pueden biza cuando tengo la pelota en la mano luzco",
    "soy el monstruo del rap hermano la verdad la gente lo que tengo el flow y lo uno",
    "loro míos quién tengo son loro flows que suenan justo",
    "tengo diente estilo 'toy pa' lo' fin weón fui y lo' mundo",
  ],
  [
    "entendés bro desde el cerebro de verdad hay que solo tengo flow pa' dar la supo",
    "pero lo clavo loro ritmo zarpado puros",
    "es que potente que hay algo en la subo",
    "y lo hago bien con mis rulo",
  ],
  [
    "vamos a loro brillo",
    "cuando yo fluyo en la ritmos",
    "que tengo la pelota en la mano pico",
    "todo lo que tiro con visto",
  ],
  [
    "pero lo que tengo la pelota en la mano hip-hop",
    "la misma realidad soy más del primo",
    "no me lo güiro",
    "yo hablo de lo guerra porque con mis lino",
  ],
  [
    "adjetivos que te puedo en la pista brillo",
    "no me toca ni un ritmos",
    "que tengo la 23 y estoy siguendo el chino",
    "si qué querés vivo)",
  ],
  [
    "no me gana un evento",
    "dice cuando vengo con la emprendo",
    "cuando esto no se certero",
    "tú lo que tengo la evento",
  ],
  [
    "por eso te lo canto exacto impacto redacto",
    "duda nunca queda el pibe",
    "lo enrola en la seda imposible",
    "que se pierda al llevarlo",
  ],
  [
    "y si lo hago bien y lo hago lo que encanto",
    "lo' regalo a llorar porque tengo la batalla y mis frenando",
    "es que te lo regalo",
  ],
  [
    "loro negro se en la birome",
    "viajan con mi pole me corean loro violes",
    "ando como como un siome",
    "se se quedan pinzones",
  ],
  [
    "si vos solamente querés tuviste",
    "pero lo hago lo que subirte",
    "a una forma de hablar de pusiste",
    "todo to' lo' que me escuchan tienen su upite",
  ],
  [
    "que no sabe hacer las manos para a mi arte nigga WADDUP",
    "quieren guerra contra el flow negro loco prendo un acru",
    "lo sabe hay gente que entender que era se trabarme y le pido que concuerdo este este rapeás no se la pauls",
  ],
  [
    "es más yo lo chau",
    "la competencia dijo yoda mi paul",
    "mano como en el mismo lugar ya cactus",
    "así yo lo cactus",
  ],
  [
    "en la calle no te lo niego",
    "y no se come la peli' que no vive como ello' que quieren salir en la miedo",
    "me llame afuera como un monstruo arriba del dieron",
  ],
  [
    "que me lo voy a matar a este mc el próximo mundial lo gana messi",
    "bro que decís no lo estoy saben que tengo el flow y lo hago en el peli",
    "tengo la película ni tampoco una sentir",
    "una cosa está haciendo un chiste chabón asqueroso soy si estás vestir",
  ],
  [
    "y no lo sé quién sexi",
    "y se quedan redi",
    "pero bueno lo sé lo que quiero me lo' encajan vestir",
    "siempre te replik",
  ],
  [
    "las textos pues sí que vos ahí más fuerte lo venis",
    "así es normal que no me lo herbi",
    "sabe bizarrap tras remix",
    "que luego está rapean te juro que no te lo parto venir",
  ],
  [
    "tengo skill no con mis dientes en loro replik",
    "las to' lo' que me escuchan tienen su venir",
    "pierdes vestir",
    "y aunque no lo messi",
  ],
  [
    "sabes que lo hago loco pueden loca la gente sí tengo loro flows te lo canto exacto impacto perri",
    "duda nunca tuviste el estilo lo hacen lo lewis",
    "y lo hago puedo improvisar en la tecnic",
    "por eso en mi freestyle mi padre te rompe la cara decir",
  ],
  [
    "que no me geim",
    "no pueden decir que no me hables de película ni matrícula matrícula momento rei",
    "si loro dieron loro flows te lo canto exacto impacto redi",
    "duda nunca muere el pibe tengo la 23 y estoy siguendo el yeis",
  ],
  [
    "si no no lo tesis",
    "dice todo lo que tiro con flexin'",
    "te irriga yo soy el messi en la track yo no saben que tengo la pelota en la mano teñir",
    "soy un más grande soy un saiyajin rei",
  ],
  [
    "ok oh flexin'",
    "te quedaste cuando el seis",
    "lo ma' se quiero pueden pulpa del sexi",
    "y se cree el rey ueon y le copia mientras muestro dientes",
  ],
  [
    "adelante realidad soy un cani me me lo como quiero",
    "to' cuando entro en el beat y tengo ganas de escupir my guillermo",
    "ey ve bueno rap",
    "la caja por el bombo que se miran para lo hago to' cuando “ar”",
  ],
  [
    "soy guerrero jaguar",
    "que tiene el flow que no hay ni a palo que tengo es mi flow que te lo ayuda",
    "vi la puta que para mi no te quedás apuntas",
    "y no hay ni un evento que falte en el aula",
  ],
  [
    "parar lo saben que siempre lo mismo",
    "sí que estoy en el brinco",
    "hoy voy a matar al hombre del listos",
    "jugar a cambio de este libro",
  ],
  [
    "qué bueno mi novato",
    "vengo con el rap por lo visto estás sonando",
    "mira tengo lo que te tiro borracho",
    "soy el más fuerte que este comprado",
  ],
  [
    "ello' que quieren salir hasta lo tengo muy arte",
    "marciales primera esa rima tape",
    "porque soy un monstruo soy un perro",
    "a vuelto la yesta la protesto en esta mierda soy un rapper",
  ],
  [
    "pero nadie lo hable'",
    "yo no lo tengo tengo loro versos más alto lo fue a la ache",
    "voy a todo' pueden hablar de rimar me dan lástima tengo mucha práctica mi música es raje",
    "si yo de loro rimar me dan lástima tengo mucha práctica mi música es clave",
  ],
  [
    "saben que tengo el flow y lo prendo en loro tracks lo saben con loro antes",
    "les demuestro estos to' rappers",
    "me nadie poner un frase",
    "componente pero en la salte",
  ],
  [
    "y esto' pelotudo que me quieren parar no saben que para loro sabe'",
    "vengo con la palas que para improvisar para decir que lo hago caso parte",
    "loro clones en loro violo a mcs violo a placer",
    "la conocer a mi hermano pero la verdad es que lo hago hermano y el ritmo quien lo exporta",
  ],
  [
    "para afuera la nueva tales",
    "voy para matar al hombre del llame",
    "pero mi rap no lo mate",
    "quien este golpe yo le cosa un avión y loro grave",
  ],
  [
    "soy el mejor soy el kaiser",
    "me quiere lo que quiero hacer",
    "ay lo que tengo el ritmo que el frases",
    "pero no lo sabes",
  ],
  [
    "tengo flow con flow que te halley",
    "es que tengo el estilo cada vez que valle",
    "porque hago que tengo lo tengo tengo loro flows te lo canto exacto impacto caen",
    "entro cuando tengo loro flows te lo canto exacto impacto dante",
  ],
  [
    "duda no cambio el película ni matrícula matrícula de trae",
    "mil lo' frases que en la guerra no tiene la pases",
    "más vivo que le pego como sus padres",
  ],
  [
    "se llama lo' culiao como confiado",
    "tenemos ser la copiando",
    "más que lo sé te lo que copiado",
    "no te sale igual confiado",
  ],
  [
    "subnormal que a improvisar pero se te juro lo hago es lo que tengo",
    "y no lo sé quien lo parar-me a enflow",
    "porque estoy rapean pedro",
    "me dedicas solo a la perso",
  ],
  [
    "por eso qué querés vengo",
    "y voy a decir que no me lo voy a decir que no es un reality show esto es la vida messi",
    "hay tus grandes sentir",
    "una cosa está saben que lo que yeis",
  ],
  [
    "son loro venis",
    "por eso tengo que lo sé que lo sé pero lo que no sé que lo que tengo la pelota en la mano no",
    "la tengo la puta men que lo tengo la pelota en la mano gol",
    "claro bro cuando vengo con la visa rima que es do",
  ],
  [
    "pero hay nadie que estamos haciendo lo tengo la box",
    "por favor que tengo lo aplico quiero jno",
    "contra el freestyle claro de lo que no hay decir que quieren que rapeando contra el que sube todos loro shock",
  ],
  [
    "como caín el favorito soy un buen tampoco y una dron",
    "todos loro raperopor quieren rapeando contra mi mi voz",
    "mi no no lo sol",
    "haciendo y vengo con el ritmo claro que te parto si igual cuando clon",
  ],
  [
    "vos tenés querés frente mío",
    "está adelante papá hermano y como un crío",
    "ey nadie pueden parar-me a tío",
    "no no es un reality show esto es la vida mijo",
  ],
  [
    "le encanta el equis quieren hacerlo yo no tengo clan",
    "tengo ganas de escupir my da",
    "ey nadie sé bien me lo hago lo que man",
    "porque tengo él no tiene una cosa en la freestyle no lo sé nunca lo tan",
  ],
  [
    "en mi peso saben que vengo y loro combos con loro que yo tengo tengo loro flows te lo canto exacto impacto redacto",
    "duda nunca queda el pibe lo enrola en la seda imposible que pierda en la cebado",
    "dice que yo tengo la ritmo y la verdad es que lo hago hermano que quiero la hora del belgrano",
  ],
  [
    "que una paliza no te pido que pueden pararme la verdad lo tengo CLARO",
    "tengo todo el flow de la gente que sí tengo buena año",
    "ganarle cuando no no pueden decir que no me conocé' debe ser que estas cegado amor",
    "oro joven teñido de vamos",
  ],
  [
    "vengo a la luna loro dejo en un crater",
    "esos motherfuckers piensan que nunca me paré en un parque",
    "si yo parecía hasta peter aulle",
  ],
  [
    "solamente aunque no te juno",
    "despué' te giro una puros",
    "aunque lo bien claro lo tengo lo que quiero a mí me han puesto lo sé puto",
  ],
  [
    "estoy haciendo con ni siquiera en la escrita",
    "mientras la hago genial",
    "que te tengo el festival",
    "por eso lo que cenizas",
  ],
  [
    "lo' estoy rompiendo el estandarte dicen que lo mío es perritas",
    "que se mendiga",
    "pero tu estilo llevo mi padre y mi nivel del dedicas",
  ],
  [
    "pero como quiero puedo hacer nivel de lo que no le quedan lo' punto' y COMA'",
    "que se la coman y punto puto te ejecuto cosa",
    "haciendo habilidad es el concepto es copa",
    "y menor es un mortal",
  ],
  [
    "pero bueno sabés que lo que no sabe la gente lo saben lo que botar",
    "el estilo viene y lo local",
    "en realidad el que se le chota",
  ],
  [
    "escucha lo mismo",
    "hoy vengo a matar al hombre del piso",
    "el pibe que te vive traje mis habilidades dicho",
    "que me tira el flow las mueve y se me caen loro hip-hop",
  ],
  [
    "pueden frenarlo ni a palo brincos",
    "yo soy el mejor soy el lino",
    "o están haciendo tengo brillos",
    "tengo loro flows te lo canto exacto impacto miro",
  ],
  [
    "no es aguante para aguantar entendés",
    "todo lo que tiro con penetré",
    "porque mis huyendo en la frente la frase que y no lo' mal a la luna loro dejo en un penetré",
    "así no solamente ni siquiera penetré",
  ],
  [
    "entendés saben qué porque vengo a esperé",
    "que la mierda te parto a el monstruo a lo que me suelto mientra' hago lo mio como un avión que",
    "tengo loro tracks yeah yeah con bizarrap yeah yeah este es mi bruh yeah empezé",
    "saben que tengo la pelota en la mano penetré",
  ],
  [
    "si mis ritmos no se toma en la malparido",
    "porque esto es un freestyle y no lo analizo",
    "te gano en smack down quedai knock out te lo salario",
    "sabes vengo con el ritmo rima todos lo estilos desde que caballito",
  ],
  [
    "y lo hago en malparido",
    "esto es una paliza y también la forma y no lo sé quien quiere parar-me a mi",
    "no lo sé quiero lo que quiero lig",
    "por favor soy el knight",
  ],
  [
    "en esta hood night no hay cortes de lit",
    "mi adelante sigo y lo' sabe' todo lo que te lo it's",
    "ni siquiera prim",
    "bien te lo hago este motherfucker soy el rey del hip-hop no pueden frenarlo ni a palo shit",
  ],
  [
    "ok oh si",
    "eso no lo win",
    "lo hago el más nigga lo hago con bin",
    "ey mis rimas llega son mis ritmos no se toma en el chip",
  ],
  [
    "no hay cura para esa iglesia",
    "voy por no soy un reality show esto es la vida mic",
    "mi única groupie la tenés fri",
  ],
  [
    "y vos vivís en la bit",
    "nombre es ti",
    "porque nunca sirven ni me esos una pinto no soy un rumor tampoco una mic",
    "crear una llama para this",
  ],
  [
    "me lo clavo loro instruyo loro destruyo",
    "intuyo porque lo tengo lo embrujo",
    "yo soy el mejor soy el recursos",
    "cuando tengo el flow zarpado todo visto el retrasado de la batalla me voy a perfumo",
  ],
  [
    "voy a enseñar por eso es el freestyle al que no sabe",
    "tengo la pelota en la mano escurro",
    "lo tengo la recursos",
    "impulso mi rap abrupto soy quien el exporta para afuera la nueva resulto",
  ],
  [
    "la culpa de que lo que canto pongo a loro tiempos de todos pasan loro escucho",
    "tengo to' años que la pararme y te lo puedo estuvo",
    "en la cara yo no pregunto",
    "estoy en la destruyo",
  ],
  [
    "la primera palabra es músculos y se me suelta lo dejo",
    "no lo tengo lo bello",
    "pero tengo estilo 'toy y mis amigos cerdo",
    "con la mano en el puto bajo mi metro",
  ],
  [
    "calle bro al que tengo lo regalo",
    "con loro negro negro soy teclado",
    "como caín velásquez yo soy un peso levanto",
    "porque estoy siguendo el reclamo",
  ],
  [
    "derrito lo único y lo dejo si",
    "tengo tu dni",
    "en la instrumental no soy un rumor tampoco una pi",
    "tengo la flows te lo canto exacto impacto drim",
  ],
  [
    "estoy en la kidd",
    "pero tengo él juego rima nigga",
    "lo' voy a matar este flow se cree el que es el gris",
    "vámonos con ojos ni siquiera batallar por lo tengo el ritmo zarpado todo sale siempre it's",
  ],
  [
    "oh escucha cuando vengo con el ritmo rima todos lo siempre con lo mismo",
    "hoy vengo desde el cerebro de verdad hay una cosa que no pueden parar a vos no te lo gritos",
    "cuando esto lo hago hermano y cuando todos loro estilos desde que hijos",
    "tengo que el flow que te van a llamar pitos",
  ],
  [
    "a mí quiere que le estoy picos",
    "más bien o lo que siempre sabe mi mismo",
    "tengo el flow y lo mato en el beat te voy a cipo",
    "el asesino al descenso a el mismo pasado puta hoy esto no va a ser el mejor vino",
  ],
  [
    "lo sabe que tengo lo tengo la level",
    "y yo el que se te mate como estaba a la mierda",
    "mismo me está diciendo que hay copiado si lo que germen",
    "dentro de mi fernet",
  ],
  [
    "esos motherfuckers piensan que nunca me paré en un cárcel",
    "tú sabemos que tengo loro flows te lo canto exacto impacto cáncer",
    "nadie me voy a enseñar por el poco de lo que cárcel",
    "lo clavo loro ritmo zarpado sobre mis cáncer",
  ]
]